[features]
seeds = false
skip-lint = false
[programs.localnet]
a_solana_demo = "9TFvj5xg3X7URQGE8PYVEtb2HZ9mrGXRiWqmsdRX6xS3"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/yangjiefeng/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
